---
- name: AWS CFN Bootstrap | Download the package.
  get_url:
    dest: /tmp/
    url: https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz

- name: AWS CFN Bootstrap | Unarchive downloaded package.
  unarchive:
    copy: no
    dest: /tmp/
    src: /tmp/aws-cfn-bootstrap-latest.tar.gz

- name: AWS CFN Bootstrap | Determine verion
  shell: ls -d */ | grep aws-cfn-bootstrap
  args:
    chdir: /tmp/
  register: aws_cfn_bootstrap_directory

- name: AWS CFN Bootstrap | Install package.
  easy_install:
    name: "/tmp/{{ aws_cfn_bootstrap_directory.stdout }}"
