---
- name: AWS CFN Bootstrap | Install supporting packages
  apt:
    name: python-pip

- name: AWS CFN Bootstrap | Download the package.
  get_url:
    dest: /tmp/
    url: https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz

- name: Ensure temporary directory exists
  file:
    path: /tmp/aws-cfn-bootstrap-latest
    mode: 0755
    state: directory

- name: AWS CFN Bootstrap | Unarchive downloaded package.
  unarchive:
    copy: no
    dest: /tmp/
    list_files: True
    src: /tmp/aws-cfn-bootstrap-latest.tar.gz
  register: cfn_bootstrap

- name: AWS CFN Bootstrap | Install package.
  pip:
    name: "/tmp/{{ cfn_bootstrap.files[0][:-1] }}"
