---
- name: AWS CFN Bootstrap | Install supporting packages
  apt:
    name: python-pip

- name: AWS CFN Bootstrap | Download the package.
  get_url:
    dest: /tmp/
    url: https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz

- name: AWS CFN Bootstrap | Unarchive downloaded package.
  unarchive:
    copy: no
    dest: /tmp/
    src: /tmp/aws-cfn-bootstrap-latest.tar.gz

- name: AWS CFN Bootstrap | Install package.
  pip:
    name: /tmp/aws-cfn-bootstrap-latest.tar.gz
